### ISSUE TITLE
Concurrent requests not working

### ISSUE THREAD

**Issue by Sleepingpirates** [dkackman/fing#19]
**Describe the bug**
Concurrent requests not working, I tried sending multiple curls and if there is an image already being produced it will raise error: 

raise Exception("busy")
Exception: busy
 
I am only using 1 gpu. rtx 3080 

**To Reproduce**
Send multiple curls at the same time. Only one goes thru

**Expected behavior**
Create a queue... 

**Additional context**
`INFO:     192.168.55.2:57374 - "GET /txt2img?prompt=test&format=json&guidance_scale=7.5&num_inference_steps=50&num_images=1&height=512&width=512&use_ldm=false HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/fastapi/routing.py", line 221, in app
    solved_result = await solve_dependencies(
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 535, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/faiz/.conda/envs/fing/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/faiz/builds/fing/src/generator/diffusion/device_pool.py", line 26, in remove_device_from_pool
    raise Exception("busy")
Exception: busy`

**Comment by hardik-a-joshi** [comment]
Same, needs to create queue,

Also, "use_ldm:  true" throws internal server error

**Comment by dkackman** [comment]
It supports 1 concurrent request per gpu. So when they are all busy it returns that error. Add another gpu and it should work. 

I thought about queuing the requests but then decided that is better handled by the caller.

**Comment by dkackman** [comment]
> Also, "use_ldm: true" throws internal server error

I cannot reproduce this. If you can with the latest code, can you create an issue with more detail?

**Comment by dkackman** [comment]
the reason I don't want the service to manage a request queue is that it then becomes possible to DDOS the service, intentionally or via a bug in an upstream app. Should some requester go rogue and spam requests it would eventually OOM the service or at a minimum block it up for a very long time as it chewed through the requests. 

By just returning an error the service is protected from that and can concentrate on generating images.

Something like:
```
  while (service not busy):
    image = call txt2img
```

is pretty easy to implement in bash or whatever you are using. And since the "busy" message is very cheap you can ping the endpoint with relative frequency though I would sleep for a couple of seconds between each inquiry.

that being said, if  for your needs you really want this on the service side replace the contents of `device_pool.py` with this:

```python
from typing import List
from .device import Device
from threading import Lock
import asyncio

mutex: Lock = Lock()

available: List[Device] = []

# TODO - avoid loading if possible by finding a device with the desired pipeline already on it


def add_device_to_pool(device: Device):
    mutex.acquire(True, 2)
    try:
        available.append(device)
    finally:
        mutex.release()


def _remove_device_from_pool():
    mutex.acquire(True, 2)
    try:
        if len(available) > 0:
            return available.pop(0)

        return None
    finally:
        mutex.release()


async def remove_device_from_pool():
    device = _remove_device_from_pool()
    while device is None:
        await asyncio.sleep(5)
        device = _remove_device_from_pool()

    return device
```

 you could build a timeout mechanism into that which might protect against what I'm referencing above

**Comment by Sleepingpirates** [comment]
@dkackman I replaced the contents of `device_pool.py` with what your provided and it works as I wanted it to. I will definitely look into the building some sort of mechanism to prevent the fallbacks of this. But thanks a lot for providing this!

**Comment by dkackman** [comment]
> @dkackman I replaced the contents of `device_pool.py` with what your provided and it works as I wanted it to. I will definitely look into the building some sort of mechanism to prevent the fallbacks of this. But thanks a lot for providing this!

cool beans. just be aware that even with a timeout you might still at some point have to deal with the service that tells you it's busy and you'll need to provide retry support in the caller. might not be an issue for how you're using it though.
